FROM ubuntu:22.04

# Actualizando el sistema base
RUN apt-get update && apt-get -y upgrade

# Asegurandonos de tener los paquetes que necesitamos y comprobamos las versiones
RUN apt-get install -y nodejs git

# Descargamos el contenedor 
RUN git clone https://github.com/cesarol/WebAngularSencilla.git

WORKDIR /WebAngularSencilla/API

# Descargamos dependencias de node
RUN npm install
