version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: dockerfile
      target: base
    volumes:
      - ./src:/Api_server
    container_name: ts-node-docker
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev