version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: dockerfile
      target: base
    container_name: ts-node-docker
    expose:
      - '5000'
    ports:
      - '5000:80'