FROM node:18-alpine as base

RUN mkdir -p /Api_server

WORKDIR /Api_server

COPY package.json /Api_server

RUN npm install

COPY . /Api_server/

FROM base as production

ENV NODE_PATH=./Api_server/build

RUN npm run build

